language: go

go:
  - 1.3

before_install:
  - go get github.com/stretchr/testify/assert
  - go get github.com/tools/godep
  - export PATH=$HOME/gopath/bin:$PATH
  - godep restore

script:
  - godep go test -v ./...
